### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by ivomarino** [rundeck-plugins/openssh-bastion-node-execution#1]
hi there, great plugin, unfortunately I always get the following issue: `Host key verification failed.`.
Setup is like that:

<img width="1116" alt="screen shot 2018-02-11 at 10 23 31" src="https://user-images.githubusercontent.com/4869961/36071880-09f80c42-0f16-11e8-8866-3730ccd4e145.png">

Connecting to the bastion host using rundeck's base ssh works fine, any ideas?
I'm running rundeck as Docker container by the way, thanks

**Comment by ahonor** [comment]
@ivomarino try adding `-o StrictHostKeyChecking=no` to the SSH Options field.

**Comment by ivomarino** [comment]
thanks for feedback @ahonor, didn't work tried also different combinations, I now use:
```
eval `ssh-agent` ; ssh-add /var/lib/rundeck/var/storage/content/keys/sysadm/id_rsa ; ssh-add -L ; ssh -A -o 'StrictHostKeyChecking no' -J ${node.bastion} -p ${node.port} ${node.username}@${node.hostname} ${exec.command}
```

as `exec` task, with `bash -c`, node example:

`<node name='foo-compute-03' tags='node,foo,production' hostname='compute-03' port='22' bastion='sysadm@first.jump.station,sysadm@second.jump.station:2221' osArch='x86_64' osFamily='linux' osName='trusty' osVersion='Ubuntu 14.04' username='sysadm'/>`

which allows me to hop between multiple nodes.

**Comment by ahonor** [comment]
@ivomarino that's a nice alternative. That can also be an example or different implementation for the plugin.

**Comment by ivomarino** [comment]
@ahonor yes, why not, happy that I could help;)

**Comment by anthonysomerset** [comment]
i since found a working config here - issue seems to be in the ProxyCommand config needs to also have StrictHostKeyChecking disabled or add the key to your server via some other means

```
Host *
  StrictHostKeyChecking no
  ForwardAgent yes
  Port 22
  ProxyCommand ssh -oStrictHostKeyChecking=no -i @bastion_ssh_key@ awx@@bastion_ssh_host@ -W %h:%p
  IdentityFile @node_ssh_key@
```

the ProxyCommand -oStrictHostKeyChecking  affects the local SSH within the rundeck box - 

the StrictHostKeyChecking for the Host config is for after the proxy session is opened and if your jumpbox has the SSH host key stored already then it is unneccesary
